2019-10-23 02:04:52,089 - selenium - ERROR - basePage  - 124 - Browser open error
Traceback (most recent call last):
  File "/root/PycharmProjects/blr.9161252.com/Common/basePage.py", line 117, in open_browser
    self.maximize_window()
  File "/root/PycharmProjects/blr.9161252.com/Common/basePage.py", line 244, in maximize_window
    self.driver.maximize_window()
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 737, in maximize_window
    self.execute(command, params)
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=77.0.3865.75)

2019-10-23 02:04:52,158 - selenium - ERROR - page_messages  - 248 - Failure of test case execution! Reason: 'NoneType' object has no attribute 'find_element'
2019-10-23 02:04:52,160 - selenium - ERROR - page_messages  - 248 - Failure of test case execution! Reason: 'NoneType' object has no attribute 'find_element'
2019-10-23 02:04:52,160 - selenium - ERROR - page_messages  - 248 - Failure of test case execution! Reason: 'NoneType' object has no attribute 'find_element'
