2019-10-24 04:39:32,921 - selenium - ERROR - page_register  - 113 - 用例执行失败，原因：Message: 

2019-10-24 04:39:44,089 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: 

2019-10-24 04:39:52,202 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: Failed to find value field

2019-10-24 04:39:52,521 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: Failed to decode response from marionette

2019-10-24 04:39:52,523 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: Tried to run command without establishing a connection

2019-10-24 04:39:52,526 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: Tried to run command without establishing a connection

2019-10-24 04:39:52,528 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: Tried to run command without establishing a connection

2019-10-24 04:39:52,533 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: Tried to run command without establishing a connection

2019-10-24 04:39:52,539 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: Tried to run command without establishing a connection

2019-10-24 04:39:52,544 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: Tried to run command without establishing a connection

2019-10-24 04:39:52,547 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: Tried to run command without establishing a connection

2019-10-24 04:39:52,549 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: Tried to run command without establishing a connection

2019-10-24 04:39:52,553 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: Tried to run command without establishing a connection

2019-10-24 04:39:52,556 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: Tried to run command without establishing a connection

2019-10-24 04:39:52,560 - selenium - ERROR - page_register  - 88 - Failure of test case execution! Reason：Message: Tried to run command without establishing a connection

2019-10-24 04:39:54,601 - selenium - ERROR - basePage  - 124 - Browser open error
Traceback (most recent call last):
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/PycharmProjects/blr.9161252.com/Common/basePage.py", line 114, in open_browser
    self.driver = webdriver.Firefox()
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/root/PycharmProjects/blr.9161252.com/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
